# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DW_edit_file_of_script.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DW_edit_file_of_script(object):
    def setupUi(self, DW_edit_file_of_script):
        DW_edit_file_of_script.setObjectName("DW_edit_file_of_script")
        DW_edit_file_of_script.resize(400, 300)
        self.TextEdit_dw_sr = QtWidgets.QTextEdit(DW_edit_file_of_script)
        self.TextEdit_dw_sr.setGeometry(QtCore.QRect(0, 10, 281, 281))
        self.TextEdit_dw_sr.setObjectName("TextEdit_dw_sr")
        self.verticalLayoutWidget = QtWidgets.QWidget(DW_edit_file_of_script)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 10, 101, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Layout_btn_edit_files = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Layout_btn_edit_files.setContentsMargins(0, 0, 0, 0)
        self.Layout_btn_edit_files.setObjectName("Layout_btn_edit_files")
        self.btn_run_files_sr = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_run_files_sr.setObjectName("btn_run_files_sr")
        self.Layout_btn_edit_files.addWidget(self.btn_run_files_sr)
        self.btn_rename_files_sr = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_rename_files_sr.setObjectName("btn_rename_files_sr")
        self.Layout_btn_edit_files.addWidget(self.btn_rename_files_sr)
        self.btn_save_files_sr = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_save_files_sr.setObjectName("btn_save_files_sr")
        self.Layout_btn_edit_files.addWidget(self.btn_save_files_sr)
        self.btn_close_DW = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_close_DW.setObjectName("btn_close_DW")
        self.Layout_btn_edit_files.addWidget(self.btn_close_DW)

        self.retranslateUi(DW_edit_file_of_script)
        QtCore.QMetaObject.connectSlotsByName(DW_edit_file_of_script)

    def retranslateUi(self, DW_edit_file_of_script):
        _translate = QtCore.QCoreApplication.translate
        DW_edit_file_of_script.setWindowTitle(_translate("DW_edit_file_of_script", "Dialog"))
        self.btn_run_files_sr.setText(_translate("DW_edit_file_of_script", "Запустить"))
        self.btn_rename_files_sr.setText(_translate("DW_edit_file_of_script", "Переименовать"))
        self.btn_save_files_sr.setText(_translate("DW_edit_file_of_script", "Сохранить"))
        self.btn_close_DW.setText(_translate("DW_edit_file_of_script", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DW_edit_file_of_script = QtWidgets.QDialog()
    ui = Ui_DW_edit_file_of_script()
    ui.setupUi(DW_edit_file_of_script)
    DW_edit_file_of_script.show()
    sys.exit(app.exec_())
