# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QW_Wind_Log.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wgt_Wind_Log(object):
    def setupUi(self, Wgt_Wind_Log):
        Wgt_Wind_Log.setObjectName("Wgt_Wind_Log")
        Wgt_Wind_Log.setEnabled(True)
        Wgt_Wind_Log.resize(371, 491)
        self.TxtBr_Wind_Log = QtWidgets.QTextBrowser(Wgt_Wind_Log)
        self.TxtBr_Wind_Log.setGeometry(QtCore.QRect(20, 20, 321, 351))
        self.TxtBr_Wind_Log.setObjectName("TxtBr_Wind_Log")
        self.btn_clear_log = QtWidgets.QPushButton(Wgt_Wind_Log)
        self.btn_clear_log.setGeometry(QtCore.QRect(30, 410, 75, 24))
        self.btn_clear_log.setObjectName("btn_clear_log")

        self.retranslateUi(Wgt_Wind_Log)
        QtCore.QMetaObject.connectSlotsByName(Wgt_Wind_Log)

    def retranslateUi(self, Wgt_Wind_Log):
        _translate = QtCore.QCoreApplication.translate
        Wgt_Wind_Log.setWindowTitle(_translate("Wgt_Wind_Log", "Form"))
        self.btn_clear_log.setText(_translate("Wgt_Wind_Log", "Очистить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wgt_Wind_Log = QtWidgets.QWidget()
    ui = Ui_Wgt_Wind_Log()
    ui.setupUi(Wgt_Wind_Log)
    Wgt_Wind_Log.show()
    sys.exit(app.exec_())
